#!/bin/bash
#export AREAS="lab308"
export AREAS="lab308"
#export AREAS="qt1feasibleseed1"
export BASE_WS_URI="http://localhost:8080/"
export HASP_URL="http://localhost:8080/"
export HA_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1M2NmN2IwMDBkMTI0MTdiODU2NDgzZjA3NDY0ZTZjMCIsImlhdCI6MTc3OTQ0OTM3MiwiZXhwIjoyMDk0ODA5MzcyfQ.2B86kPA0PG2n4QC1fFwYYEKbJiMI3Dh_NVda_EutOQs"
export HA_URL="ws://localhost:8123/api/websocket"
export TD_SOSA_ENV_VAR_OVERRIDES="$(cat tdsosa-env-overrides.lab308e.json)"
export TD_SOSA_PROPERTY_RANGES="$(cat tdsosa-property-ranges.lab308e.json)"
export TD_SOSA_SETTLING_TIMES="$(cat tdsosa-settling-times.lab308e.json)"
#export TD_SOSA_ENV_VAR_OVERRIDES="$(cat tdsosa-env-overrides.sample.json)"
export SEMANTIC_CONFIG="$(cd "$(dirname "$0")" && pwd)/lab308.yaml"
