#!/bin/bash
#export AREAS="lab308"
export AREAS="lab308e"
#export AREAS="qt1feasibleseed1"
export BASE_WS_URI="http://localhost:8080/"
export HASP_URL="http://localhost:8080/"
export HA_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2MTcxYmQ1NGRiNDA0NmRiYjYxNWI1MDRkYTA4ZWM5YiIsImlhdCI6MTc3MjE5NzI0MCwiZXhwIjoyMDg3NTU3MjQwfQ.tWqiBqib3Su9SNFWppghGpHmsv4KAfhRqV1gmTP2UEo"
export HA_URL="ws://localhost:8123/api/websocket"
export TD_SOSA_ENV_VAR_OVERRIDES="$(cat tdsosa-env-overrides.lab308e.json)"
#export TD_SOSA_ENV_VAR_OVERRIDES="$(cat tdsosa-env-overrides.sample.json)"
