#!/usr/bin/env python3
"""
SimuHome -> SAREF/SOSA/TD-SOSA mapping tables (Phase A) and Thing Descriptions (Phase B).

Phase A scans the benchmark YAML, resolves every Matter fact against the vendored
registry, and emits eight reviewable mapping tables plus an inventory and a
coverage report. It then HALTS: no Thing Descriptions are produced until a human
has resolved the `todo` rows and confirmed the `review` ones.

  python tests/simuhome/td/convert.py --phase-a
  python tests/simuhome/td/convert.py --phase-a --input /path/to/benchmark
  python tests/simuhome/td/convert.py --phase-b     # gated; refuses while todos remain

Phase A is idempotent: rerunning regenerates machine-owned fields while
preserving human edits (see tables.merge_rows).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml

if __package__ in {None, ""}:  # allow `python tests/simuhome/td/convert.py`
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from td import registry_access, reports, scan, tables  # noqa: F401
    from td.tables import APPROVED, AUTO, REVIEW, TODO
else:
    from . import registry_access, reports, scan, tables
    from .tables import APPROVED, AUTO, REVIEW, TODO

TD_DIR = Path(__file__).resolve().parent
MAPPINGS_DIR = TD_DIR / "mappings"
OUT_DIR = TD_DIR / "out"
REPORTS_DIR = OUT_DIR / "reports"
CACHE_PATH = OUT_DIR / ".scan_cache.json"
DEFAULT_INPUT = TD_DIR.parents[3] / "SimuHome" / "data" / "benchmark"

TABLE_ORDER = [
    "attribute_map",
    "device_type_map",
    "room_map",
    "observable_properties",
    # Which attribute each command writes: verified links promote the
    # property classes below to `auto`.
    "command_targets",
    # Review this before actuatable_properties: approving a class here promotes
    # every family leaf beneath it.
    "property_classes",
    "actuatable_properties",
    "internal_properties",
    "actuation_effects",
    "sensing",
    "ha_binding",
]


class _Dumper(yaml.SafeDumper):
    """Block style everywhere, so the tables stay diffable and hand-editable."""


def _represent_none(dumper: yaml.Dumper, _data: Any) -> yaml.Node:
    return dumper.represent_scalar("tag:yaml.org,2002:null", "null")


_Dumper.add_representer(type(None), _represent_none)


def _write_yaml(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "# GENERATED by tests/simuhome/td/convert.py --phase-a\n"
            "# Edit freely. Set `status: approved` on a row to protect it from\n"
            "# regeneration; machine-owned fields are refreshed on every run.\n"
        )
        yaml.dump(
            payload, handle, Dumper=_Dumper, sort_keys=False,
            default_flow_style=False, allow_unicode=True, width=100,
        )


def _read_yaml(path: Path) -> Dict[str, Any]:
    if not path.is_file():
        return {}
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def _approved_property_classes() -> set:
    """Cluster-level classes a human has approved, so leaves can inherit."""
    document = _read_yaml(MAPPINGS_DIR / "property_classes.yaml")
    return {
        row["key"]
        for row in document.get("rows", [])
        if row.get("status") == APPROVED
    }


def _generate(corpus: scan.Corpus) -> Dict[str, Any]:
    attribute_rows = tables.build_attribute_map(corpus)
    return {
        "attribute_map": attribute_rows,
        "device_type_map": tables.build_device_type_map(corpus),
        "room_map": tables.build_room_map(corpus),
        "observable_properties": tables.build_observable_properties(corpus),
        "command_targets": tables.build_command_targets(corpus),
        "property_classes": tables.build_property_classes(corpus, attribute_rows),
        "actuatable_properties": tables.build_actuatable_properties(
            corpus, attribute_rows, approved_classes=_approved_property_classes()
        ),
        "internal_properties": tables.build_internal_properties(corpus, attribute_rows),
        "actuation_effects": tables.build_actuation_effects(corpus),
        "sensing": tables.build_sensing(corpus),
        "ha_binding": tables.build_ha_binding(corpus),
    }


def phase_a(args: argparse.Namespace) -> int:
    input_dir = Path(args.input).expanduser().resolve()
    if not input_dir.is_dir():
        print(f"Input directory not found: {input_dir}", file=sys.stderr)
        print("Pass --input /path/to/SimuHome/data/benchmark", file=sys.stderr)
        return 2

    reg = registry_access.get_registry()
    print(f"[phase-a] Matter data model: {reg.provenance}", flush=True)
    print(f"[phase-a] Scanning {input_dir}", flush=True)

    corpus = scan.scan(
        str(input_dir),
        read_titles=not args.no_json,
        cache_path=None if args.no_cache else str(CACHE_PATH),
    )
    print(
        f"[phase-a] {corpus.episodes} episodes, {len(corpus.families)} device families, "
        f"{len(corpus.rooms)} rooms, {len(corpus.attributes)} distinct cluster.attribute",
        flush=True,
    )
    if corpus.unresolved:
        print(
            f"[phase-a] WARNING {len(corpus.unresolved)} unresolved against the registry: "
            + ", ".join(sorted(corpus.unresolved)),
            file=sys.stderr,
        )

    generated = _generate(corpus)
    merge_stats: Dict[str, Dict[str, int]] = {}
    written: Dict[str, Any] = {}

    for name in TABLE_ORDER:
        payload = generated[name]
        path = MAPPINGS_DIR / f"{name}.yaml"
        prior = _read_yaml(path)

        if isinstance(payload, dict):  # ha_binding carries extra top-level sections
            merged_rows, stats = tables.merge_rows(prior.get("rows"), payload["rows"])
            body: Any = dict(payload)
            body["rows"] = merged_rows
        else:
            merged_rows, stats = tables.merge_rows(prior.get("rows"), payload)
            body = merged_rows

        merge_stats[name] = stats
        document = tables.envelope(
            body, table=name, corpus=corpus, include_timestamp=not args.no_timestamp
        )
        _write_yaml(path, document)
        written[name] = document
        counts = tables.count_statuses(document)
        print(
            f"[phase-a] {name:<24} rows={sum(counts.values()):<4} "
            f"auto={counts[AUTO]:<4} review={counts[REVIEW]:<4} todo={counts[TODO]:<3} "
            f"approved={counts[APPROVED]}",
            flush=True,
        )

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (REPORTS_DIR / "inventory.md").write_text(
        reports.inventory(corpus, written), encoding="utf-8"
    )
    (REPORTS_DIR / "coverage.md").write_text(
        reports.coverage(corpus, written, merge_stats), encoding="utf-8"
    )

    total_todo = sum(tables.count_statuses(doc)[TODO] for doc in written.values())
    total_review = sum(tables.count_statuses(doc)[REVIEW] for doc in written.values())

    print()
    print(f"Wrote {len(TABLE_ORDER)} tables to {MAPPINGS_DIR}")
    print(f"Wrote inventory.md and coverage.md to {REPORTS_DIR}")
    print()
    print(f"Phase A complete — {total_review} row(s) to review, {total_todo} `todo` to resolve.")
    print("Review and edit mappings/*.yaml, resolve all `todo`, then re-run in --phase-b mode.")
    return 0


def phase_b(args: argparse.Namespace) -> int:
    """Gated. Phase B is not implemented until the tables are approved.

    DESIGN NOTE for whoever implements this
    ---------------------------------------
    `mappings/` cannot supply everything Phase B needs. The tables are
    type-level by construction, but `tdsosa:affordsProperty` points at an
    ANONYMOUS INSTANCE carrying that one device's constraints -- Home Assistant
    fixes no range per device type (the climate entities in this corpus alone
    carry 42 distinct min_temp and 70 distinct max_temp values), so limits are a
    fact about a deployed device, not about "TV brightness" in general.

    Phase B must therefore read the per-episode HA YAML alongside the tables:

      * climate entities  -> `min_temp`, `max_temp`, `target_temp_step`
      * LevelControl      -> the `MinLevel` / `MaxLevel` sensor_metadata rows,
                             whose values live in the per-episode YAML
      * humidity / temp   -> the `Min/MaxMeasuredValue` sensor_metadata rows
      * FanControl        -> `FanModeSequence`, which declares which of
                             Off/Low/Medium/High/Auto THIS device supports and so
                             constrains the legal values of `FanMode`

    Treat FanModeSequence as advisory, not authoritative. In this corpus every
    device declares `OffLowHigh` (no Medium) while a large share sit at
    `FanMode: Medium` and queries ask for a "medium" fan, so a schema derived
    from it would reject both the live state and the user's request. The enum in
    ha_binding.yaml (`off, low, medium, high`) is what an action input should
    use; emit FanModeSequence alongside as a capability statement.

    Each becomes `qudt:minValue` / `qudt:maxValue` on the blank node, typed by
    `property_type` from actuatable_properties.yaml. The class hierarchy goes to
    out/vocab/ex.ttl; no TD may reference a node defined outside itself.

    ASSERT ONE TYPE PER NODE
    ------------------------
    Emit only the most specific class; never a superclass alongside it. RDF is
    not a place to restate what is already entailed:

        [ a ex:DimmableLightOnOff ]                              # yes
        [ a ex:DimmableLightOnOff, sosa:ActuatableProperty ]     # no, redundant

    `sosa:ActuatableProperty` follows twice over -- from
    `ex:DimmableLightOnOff rdfs:subClassOf ex:OnOff rdfs:subClassOf
    sosa:ActuatableProperty` in ex.ttl, and independently from the v2 ontology's
    restriction on tdsosa:ActuatablePropertyAffordance:

        tdsosa:ActuatablePropertyAffordance rdfs:subClassOf [
            owl:onProperty tdsosa:affordsProperty ;
            owl:someValuesFrom sosa:ActuatableProperty ] .

    so a reasoner infers it from the affordance's own type without ex.ttl loaded.
    The same applies to `a ex:Illuminance` (not `, sosa:ObservableProperty`) and
    `a ex:Bathroom` (not `, sosa:FeatureOfInterest, s4bldg:BuildingSpace`) --
    declare those parents once, in ex.ttl.

    WRITABLE IS NOT THE SAME AS EFFECTFUL
    -------------------------------------
    12 of the 25 actuatable attributes carry `has_immediate_effect: false` --
    installed capability (ControlSequenceOfOperation, WindowCovering.Mode),
    power-restoration defaults (StartUp*), and timing parameters (OnTime,
    transition times). Emit them as property affordances with `readOnly: false`,
    since Matter genuinely permits the write, but emit NO
    `tdsosa:hasEffectActuation` and no action for them: claiming an
    environmental effect would be false. `no_effect_reason` says which kind.

    Three deliberate exceptions, all on the Thing itself:
      * `td:Thing` -- required by the TD 1.1 spec for consumers that do not reason.
      * `sosa:Sensor` / `sosa:Actuator` -- a ROLE, not a superclass of the device
        class. One device can be both, and which it is depends on the affordances
        it ended up with, so it is not derivable from `ex:DimmableLight`.
      * the SAREF parent alongside the `ex:` class, i.e. emit BOTH
        `ex:DimmableLight` and `saref:Actuator` from device_type_map's
        `td_types`. The `ex:` class names the exact device kind; the `saref:`
        class places it in the standard taxonomy so a consumer that never loads
        ex.ttl still knows what it is looking at. Redundant under reasoning,
        deliberately so at the Thing level where interop matters most.

    Note there is no `saref:Lighting`: SAREF core declares only Actuator,
    Appliance, HVAC, Meter and Sensor under saref:Device, and its light-related
    terms (saref:Light, saref:LightSwitch) are deprecated Property classes.
    """
    outstanding: List[str] = []
    for name in TABLE_ORDER:
        document = _read_yaml(MAPPINGS_DIR / f"{name}.yaml")
        if not document:
            print(f"Missing mapping table: {name}.yaml — run --phase-a first.", file=sys.stderr)
            return 2
        rows = document.get("rows", [])
        for row in rows:
            if row.get("status") == TODO:
                outstanding.append(f"{name}: {row.get('key')}")

    if outstanding:
        print(f"Refusing to convert: {len(outstanding)} `todo` row(s) remain.", file=sys.stderr)
        for item in outstanding[:40]:
            print(f"  - {item}", file=sys.stderr)
        if len(outstanding) > 40:
            print(f"  … and {len(outstanding) - 40} more", file=sys.stderr)
        return 1

    print("Phase B is not implemented yet.", file=sys.stderr)
    print("The Phase A gate passes (no `todo` rows), so it is ready to be built.", file=sys.stderr)
    return 1


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(
        description="SimuHome -> SAREF/SOSA/TD-SOSA mapping tables and Thing Descriptions."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--phase-a", action="store_true", help="Scan and emit mapping tables, then halt")
    mode.add_argument("--phase-b", action="store_true", help="Emit Thing Descriptions (gated)")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="SimuHome benchmark directory")
    parser.add_argument("--no-json", action="store_true",
                        help="Skip the one-time BasicInformation.ProductName lookup")
    parser.add_argument("--no-cache", action="store_true", help="Ignore the scan cache")
    parser.add_argument("--no-timestamp", action="store_true",
                        help="Omit generated_at_utc, for byte-identical reruns in CI")
    args = parser.parse_args(argv)

    return phase_a(args) if args.phase_a else phase_b(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
