# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
# SPDX-License-Identifier: Apache-2.0
spring:
  application:
    name: interaction-solver-agent
  jackson:
    default-property-inclusion: NON_NULL
  main:
    banner-mode: off
    web-application-type: reactive
  reactor:
    context-propagation: auto
  graphql:
    graphiql:
      enabled: true

server:
  port: 8083

arc:
  cors:
    enabled: true
  scripts:
    enabled: false
    folder: agents
    hotReload:
      enable: true
      delay: PT1S
  chat:
    ui:
      enabled: true
  subscriptions:
    events:
      enable: true

logging:
  level:
    root: WARN
    org.eclipse.lmos.arc: INFO
    org.eclipse.lmos.arc.app.config: INFO
    # ArcDSL: DEBUG

management:
  otlp:
    tracing:
      endpoint: http://localhost:6006/v1/traces
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  server:
    port: 9093
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus,metrics,info,health
  endpoint:
    metrics:
      enabled: true
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

envmonitoring:
  agent:
    url: http://localhost:8081
envexplorer:
  agent:
    url: http://localhost:8082
