# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

arc:
  ai:
    clients:
      - id: test-gemini
        model-name: gemini-2.0-flash
        api-key: ${GEMINI_API_KEY}
        client: gemini