"""InteractionSolver Agent — goal planning and execution.

SPADE agent that receives GOAL_REQUEST messages, gathers planning
context from EnvExplorer, and returns a behavior-tree plan (either
recovered from signifiers or generated by the LLM via AsyncBTPlanner).
"""

import asyncio
import json
import logging
import os
from typing import Any, Dict, List, Optional

from spade.agent import Agent
from spade.message import Message as SpadeMessage
from spade.template import Template

from ...shared.protocols.agent_protocol import IAgent
from ...shared.models.messages import (
    Message,
    MessageType,
    META_CORRELATION_ID,
    META_CONVERSATION_ID,
    ensure_correlation_id,
    extract_conversation_id,
    serialize_body,
)
from ...shared.utils.spade_rpc import rpc_call, RpcTimeoutError, send_via_router
from ...shared.utils.demo_log import demo
from ...shared.community.community_client import CommunitySignifierClient
from ...bt_planning.planning.bt_planner import AsyncBTPlanner
from ...bt_planning.signifier_bridge import build_bt_from_signifiers

from .behaviours import EnvironmentReadyBehaviour, GoalRequestBehaviour
from .utils import (
    LLMClientConfig,
    build_llm_client,
    match_workspace,
    merge_signifier_matches,
    parse_or_empty,
    query_community_signifier_match,
    query_local_signifier_match,
)
from ..user_assistant.models import Intent

logger = logging.getLogger("InteractionSolver")

# Fallback defaults used only when yaml is missing a key.
_DEFAULT_CONTEXT_TIMEOUT_S = 10.0
_DEFAULT_COMMUNITY_TIMEOUT_S = 10.0
_DEFAULT_MAX_PLANNING_ATTEMPTS = 3


class InteractionSolverAgent(Agent, IAgent):
    """InteractionSolver agent for planning and goal resolution.

    Responsibilities:
    - Receive goal requests from UserAssistant (``GoalRequestBehaviour``).
    - Gather planning context (affordances + state) from EnvExplorer.
    - Generate behavior tree plans, preferring signifier reuse
      (fast path) and falling back to LLM-based generation.
    """

    def __init__(
        self,
        jid: str,
        password: str,
        config: Dict[str, Any],
        target_jids: Optional[Dict[str, str]] = None,
    ):
        super().__init__(jid, password)
        self.config = config or {}
        self.target_jids = target_jids or {}

        self.environment_ready = False
        self._environment_ready_event: asyncio.Event = asyncio.Event()
        self._last_env_ready_payload: Optional[Dict[str, Any]] = None
        self.env_explorer_jid: Optional[str] = None

        # Cache the last known environment context so we can build plans from
        # signifiers without re-querying EnvExplorer for capabilities/state.
        self._cached_affordances: List[Dict[str, Any]] = []
        self._cached_state_payload: Dict[str, Any] = {}
        self._cached_affordance_by_id: Dict[str, Dict[str, Any]] = {}

        # ── LLM client ──────────────────────────────────────────────
        self._llm_cfg: LLMClientConfig = build_llm_client(self.config)
        self.llm_client = self._llm_cfg.client
        self.model = self._llm_cfg.model
        self.base_url = self._llm_cfg.base_url
        self.temperature = self._llm_cfg.temperature
        self.reasoning_effort = self._llm_cfg.reasoning_effort
        self.max_tokens = self._llm_cfg.max_tokens
        self.max_completion_tokens = self._llm_cfg.max_completion_tokens

        # ── Timeouts / limits (from yaml with small fallbacks) ──────
        context_cfg = (self.config.get("planning", {}) or {}).get("context_gathering", {}) or {}
        self.context_timeout: float = float(
            context_cfg.get("timeout", _DEFAULT_CONTEXT_TIMEOUT_S)
        )
        # ``GoalRequestBehaviour`` waits this long for EnvExplorer discovery.
        self.env_ready_timeout: float = self.context_timeout

        planning_llm = (self.config.get("planning", {}) or {}).get("llm_planning", {}) or {}
        max_attempts = int(
            planning_llm.get("max_planning_attempts", _DEFAULT_MAX_PLANNING_ATTEMPTS)
        )
        self.bt_planner = AsyncBTPlanner(max_attempts=max_attempts)

        # ── Community signifier client (optional) ───────────────────
        community_cfg = (self.config.get("planning", {}) or {}).get("community", {}) or {}
        community_url = community_cfg.get("api_url") or os.getenv("COMMUNITY_API_URL")
        self.community_enabled = bool(community_cfg.get("enabled", bool(community_url)))
        self.community_client: Optional[CommunitySignifierClient] = None
        if self.community_enabled and community_url:
            community_timeout = float(
                community_cfg.get("timeout", _DEFAULT_COMMUNITY_TIMEOUT_S)
            )
            self.community_client = CommunitySignifierClient(
                api_url=community_url, timeout=community_timeout
            )

    # ── Environment-ready signalling ────────────────────────────────

    def mark_environment_ready(
        self,
        *,
        sender_jid: Optional[str] = None,
        payload: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.environment_ready = True
        if sender_jid:
            self.env_explorer_jid = sender_jid
        if payload is not None:
            self._last_env_ready_payload = payload
        if not self._environment_ready_event.is_set():
            self._environment_ready_event.set()

    async def await_environment_ready(self, timeout: float = 10.0) -> bool:
        """Wait until EnvExplorer has completed initial discovery.

        - If already ready: return immediately.
        - Else: try a capabilities RPC (covers missed notifications).
        - Else: wait for the ENV_DISCOVERY_COMPLETE event (up to ``timeout``).
        """
        if self.environment_ready:
            return True

        try:
            raw = await self._query_env_explorer(
                message_type=MessageType.ENV_CAPABILITIES_REQUEST.value,
                body={"query": "all"},
                expect_type=MessageType.ENV_CAPABILITIES_RESPONSE.value,
            )
            payload = json.loads(raw or "{}")
            if payload.get("discovery_complete") is True:
                self.mark_environment_ready(payload=payload)
                return True
        except Exception:
            pass

        try:
            await asyncio.wait_for(self._environment_ready_event.wait(), timeout=timeout)
            return self.environment_ready
        except asyncio.TimeoutError:
            return False

    # ── SPADE lifecycle ─────────────────────────────────────────────

    async def setup(self):
        await super().setup()

        env_ready_template = Template()
        env_ready_template.set_metadata("type", MessageType.ENV_DISCOVERY_COMPLETE.value)
        self.add_behaviour(EnvironmentReadyBehaviour(), template=env_ready_template)

        goal_template = Template()
        goal_template.set_metadata("type", MessageType.GOAL_REQUEST.value)
        self.add_behaviour(GoalRequestBehaviour(), template=goal_template)

        temp_display = "default" if self.model.startswith("o") else self.temperature
        logger.info(
            demo("InteractionSolver booting (model=%s, base_url=%s, temperature=%s, reasoning_effort=%s)"),
            self.model,
            self.base_url,
            temp_display,
            self.reasoning_effort or "default",
        )
        logger.info("InteractionSolverAgent initialized (pure SPADE + direct LLM planning).")

    async def start(self, *args, **kwargs) -> None:
        return await super().start(*args, **kwargs)

    async def stop(self) -> None:
        return await super().stop()

    # ── IAgent protocol ─────────────────────────────────────────────

    async def send_message(self, message: Message) -> bool:
        if isinstance(message, SpadeMessage):
            await send_via_router(self, message)
            return True

        spade_msg = SpadeMessage(to=message.receiver)
        spade_msg.set_metadata("type", message.message_type.value)
        for key, value in (message.metadata or {}).items():
            if value is not None:
                spade_msg.set_metadata(key, str(value))

        corr_id = ensure_correlation_id(message.metadata)
        spade_msg.set_metadata(META_CORRELATION_ID, str(corr_id))

        conv_id = extract_conversation_id(message.conversation_id, message.metadata)
        if conv_id:
            spade_msg.thread = conv_id
            spade_msg.set_metadata(META_CONVERSATION_ID, conv_id)

        spade_msg.body = serialize_body(message.content)
        await send_via_router(self, spade_msg)
        return True

    async def receive_message(self, message: Message) -> None:
        # Behaviours route incoming messages via SPADE templates.
        return

    # ── EnvExplorer RPC ────────────────────────────────────────────

    async def _query_env_explorer(
        self,
        message_type: str,
        body: Dict[str, Any],
        expect_type: str,
    ) -> str:
        """Send a SPADE message to EnvExplorer and return the response body."""
        explorer_jid = self.target_jids.get("explorer")
        if not explorer_jid:
            return json.dumps({"error": "explorer_jid_not_configured"})

        try:
            result = await rpc_call(
                self,
                to_jid=explorer_jid,
                request_type=message_type,
                body=body,
                expect_type=expect_type,
                timeout=self.context_timeout,
            )
            return result.body or ""
        except RpcTimeoutError:
            return json.dumps({"error": "timeout"})
        except Exception as e:
            return json.dumps({"error": "rpc_failed", "detail": str(e)})

    # ── Planning orchestration ─────────────────────────────────────

    async def _generate_plan(
        self,
        intents: List[Intent],
        workspace_id: Optional[str] = None,
        intent_type: Optional[str] = None,
    ) -> str:
        """Gather context and generate a BT JSON IR plan.

        Returns a JSON string with the plan in behavior-tree format:
        ``{plan_type, tree, explanation, intents, intent_type, impossible?,
        signifier_reuse?}``.
        """
        intents = [i for i in (intents or []) if i.to_query_string().strip()]
        if not intents:
            return json.dumps(
                {
                    "plan_type": "behavior_tree",
                    "error": "missing_intents",
                    "detail": "No intents provided.",
                    "tree": None,
                    "intents": [],
                    "intent_type": intent_type,
                },
                indent=2,
            )

        intent_strings = [i.to_query_string() for i in intents]

        # Fast-path: if every intent has a signifier match, build the BT
        # directly without calling EnvExplorer for capabilities/state or the LLM.
        reused_plan = await self._try_build_plan_from_signifiers(
            intents, workspace_id=workspace_id, intent_type=intent_type
        )
        if reused_plan is not None:
            logger.info(demo("BT recovered from signifiers (no EnvExplorer context queries, no LLM)"))
            return json.dumps(reused_plan, indent=2)

        try:
            context = await self._gather_planning_context(
                intent_strings, workspace_id=workspace_id, intent_type=intent_type
            )
        except Exception as e:
            logger.warning(f"Context gathering failed: {e}")
            return json.dumps(
                {
                    "plan_type": "behavior_tree",
                    "error": "context_gathering_failed",
                    "detail": str(e),
                    "tree": None,
                    "intents": [i.to_dict() for i in intents],
                    "intent_type": intent_type,
                },
                indent=2,
            )

        try:
            result = await self.bt_planner.generate_bt(
                intents=intent_strings,
                affordances=context.get("affordances", []),
                state=context.get("state"),
                signifier_hints=context.get("signifier_matches"),
                client=self.llm_client,
                model=self.model,
                temperature=self.temperature if not self.model.startswith("o") else None,
                reasoning_effort=self.reasoning_effort,
                max_completion_tokens=self.max_completion_tokens,
            )
        except Exception as e:
            logger.warning(f"BT generation failed: {e}")
            return json.dumps(
                {
                    "plan_type": "behavior_tree",
                    "error": "plan_generation_failed",
                    "detail": str(e),
                    "tree": None,
                    "intents": [i.to_dict() for i in intents],
                    "intent_type": intent_type,
                },
                indent=2,
            )

        output: Dict[str, Any] = {
            "plan_type": "behavior_tree",
            "tree": result.get("tree") or None,
            "explanation": result.get("explanation", ""),
            "intents": [i.to_dict() for i in intents],
            "workspace_id": workspace_id,
            "intent_type": intent_type,
        }
        if result.get("impossible"):
            output["impossible"] = True

        return json.dumps(output, indent=2)

    async def _try_build_plan_from_signifiers(
        self,
        intents: List[Intent],
        workspace_id: Optional[str] = None,
        intent_type: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Try to build a BT JSON IR directly from signifier matches.

        EnvExplorer hosts the signifier engine so we still query it via
        SIGNIFIER_MATCH_REQUEST here, but we intentionally skip
        ENV_CAPABILITIES_REQUEST / ENV_STATE_REQUEST on this fast path.
        Returns ``None`` if any intent lacks a usable match.
        """
        intent_strings = [i.to_query_string() for i in intents]
        try:
            signifier_matches = await self._gather_signifier_matches(
                intent_strings,
                workspace_id=workspace_id,
                intent_type=intent_type,
                structured_intents=[i.to_dict() for i in intents],
            )
        except Exception:
            return None

        if not isinstance(signifier_matches, dict) or not signifier_matches:
            return None

        tree = build_bt_from_signifiers(signifier_matches, intents)
        if tree is None:
            return None

        signifier_ids: List[str] = []
        for intent_str in intent_strings:
            match_data = signifier_matches.get(intent_str, {})
            if isinstance(match_data, dict):
                finals = match_data.get("final_matches", [])
                signifier_ids.extend(str(f) for f in finals)

        return {
            "plan_type": "behavior_tree",
            "tree": tree,
            "explanation": "Plan recovered from signifiers (no LLM call needed).",
            "intents": [i.to_dict() for i in intents],
            "workspace_id": workspace_id,
            "intent_type": intent_type,
            "signifier_reuse": True,
            "signifier_ids": signifier_ids,
        }

    async def _gather_planning_context(
        self,
        intents: List[str],
        workspace_id: Optional[str] = None,
        intent_type: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Pull affordances + state from EnvExplorer and attach signifier hints."""
        logger.info(demo("Gathering context from EnvExplorer (workspace_id=%r)"), workspace_id)
        raw_aff, raw_state = await asyncio.gather(
            self._query_env_explorer(
                message_type=MessageType.ENV_CAPABILITIES_REQUEST.value,
                body={"query": "all"},
                expect_type=MessageType.ENV_CAPABILITIES_RESPONSE.value,
            ),
            self._query_env_explorer(
                message_type=MessageType.ENV_STATE_REQUEST.value,
                body={},
                expect_type=MessageType.ENV_STATE_RESPONSE.value,
            ),
        )

        aff_payload = parse_or_empty(raw_aff)
        state_payload = parse_or_empty(raw_state)

        affordances = aff_payload.get("affordances") or aff_payload.get("capabilities") or []
        try:
            raw_artifacts = state_payload.get("artifacts") if isinstance(state_payload, dict) else None
            artifacts_count = len(raw_artifacts) if isinstance(raw_artifacts, dict) else 0
        except Exception:
            artifacts_count = 0

        logger.info(
            demo("Context snapshot: affordances=%s artifacts_in_state=%s"),
            len(affordances) if isinstance(affordances, list) else "?",
            artifacts_count,
        )

        if workspace_id:
            if isinstance(affordances, list):
                affordances = [
                    a for a in affordances
                    if isinstance(a, dict) and match_workspace(a.get("workspace_id"), workspace_id)
                ]

            if isinstance(state_payload, dict) and isinstance(state_payload.get("artifacts"), dict):
                filtered_artifacts: Dict[str, Any] = {}
                for aid, ainfo in state_payload.get("artifacts", {}).items():
                    if isinstance(ainfo, dict) and match_workspace(ainfo.get("workspace_id"), workspace_id):
                        filtered_artifacts[aid] = ainfo
                state_payload = {**state_payload, "artifacts": filtered_artifacts}

            logger.info(
                demo("Workspace scoping applied: affordances=%s artifacts_in_state=%s workspace_id=%r"),
                len(affordances) if isinstance(affordances, list) else "?",
                len(state_payload.get("artifacts") or {}) if isinstance(state_payload, dict) else "?",
                workspace_id,
            )

        signifier_matches: Dict[str, Any] = {}
        try:
            signifier_matches = await self._gather_signifier_matches(
                intents, workspace_id=workspace_id, intent_type=intent_type
            )
        except Exception:
            signifier_matches = {}

        # Cache the most recent context snapshot for future signifier-only planning.
        try:
            self._cached_affordances = affordances if isinstance(affordances, list) else []
            self._cached_state_payload = state_payload if isinstance(state_payload, dict) else {}
            self._cached_affordance_by_id = {}
            if isinstance(self._cached_affordances, list):
                for a in self._cached_affordances:
                    if not isinstance(a, dict):
                        continue
                    aid = str(a.get("affordance_id") or "").strip()
                    if aid:
                        self._cached_affordance_by_id[aid] = a
        except Exception:
            pass

        return {
            "intents": intents,
            "affordances": affordances,
            "state": state_payload.get("state") or state_payload,
            "signifier_matches": signifier_matches,
        }

    async def _gather_signifier_matches(
        self,
        intents: List[str],
        workspace_id: Optional[str] = None,
        intent_type: Optional[str] = None,
        structured_intents: Optional[List[dict]] = None,
    ) -> Dict[str, Any]:
        """Ask EnvExplorer (and optionally the community API) for signifier matches."""
        intents = [str(i).strip() for i in (intents or []) if str(i).strip()]
        if not intents:
            return {}

        intent_to_structured: Dict[str, dict] = {}
        if structured_intents and len(structured_intents) == len(intents):
            for intent_str, si in zip(intents, structured_intents):
                if isinstance(si, dict):
                    intent_to_structured[intent_str] = si

        # Local EnvExplorer RPCs.
        local_out: Dict[str, Any] = {}
        if self.target_jids.get("explorer"):
            local_results = await asyncio.gather(
                *[
                    query_local_signifier_match(
                        self._query_env_explorer,
                        i,
                        workspace_id,
                        intent_type,
                        intent_to_structured.get(i),
                    )
                    for i in intents
                ],
                return_exceptions=True,
            )
            for intent, res in zip(intents, local_results):
                if isinstance(res, Exception):
                    local_out[intent] = {"error": "signifier_query_failed", "detail": str(res)}
                else:
                    local_out[intent] = res

        # Community signifier API.
        community_out: Dict[str, Any] = {}
        if self.community_client:
            community_results = await asyncio.gather(
                *[query_community_signifier_match(self.community_client, i) for i in intents],
                return_exceptions=True,
            )
            for intent, res in zip(intents, community_results):
                if isinstance(res, Exception):
                    community_out[intent] = {}
                else:
                    community_out[intent] = res if isinstance(res, dict) else {}

        out = merge_signifier_matches(local_out, community_out, intents)
        self._log_signifier_search(out)
        return out

    @staticmethod
    def _log_signifier_search(results: Dict[str, Any]) -> None:
        """Emit demo-friendly summary lines for each intent's match result."""
        for intent, payload in results.items():
            if not isinstance(payload, dict):
                continue
            if payload.get("error"):
                logger.info(demo("Signifier search failed: intent=%r error=%s"), intent, payload.get("error"))
                continue

            matches = payload.get("matches") if isinstance(payload.get("matches"), list) else []
            finals = payload.get("final_matches") if isinstance(payload.get("final_matches"), list) else []
            total = payload.get("total_signifiers")
            community_count = sum(1 for m in matches if isinstance(m, dict) and m.get("source") == "community")

            if finals:
                logger.info(
                    demo("Signifier search: intent=%r matches=%d (community=%d) final=%d top=%s"),
                    intent,
                    len(matches),
                    community_count,
                    len(finals),
                    finals[0],
                )
            else:
                logger.info(
                    demo("Signifier search: intent=%r matches=%d (community=%d) final=0 stored_total=%s"),
                    intent,
                    len(matches),
                    community_count,
                    total if total is not None else "?",
                )
